# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: eza-community.eza
PackageVersion: 0.20.8
PackageLocale: en-US
Publisher: eza community
PublisherUrl: https://eza.rocks
PublisherSupportUrl: https://github.com/eza-community/eza/issues
PackageName: eza
PackageUrl: https://github.com/eza-community/eza
License: MIT
LicenseUrl: https://github.com/eza-community/eza/blob/main/LICENCE
ShortDescription: A modern, maintained replacement for ls, built on exa.
Description: |-
  eza is a modern, maintained replacement for the venerable file-listing
  command-line program ls that ships with Unix and Linux operating systems,
  giving it more features and better defaults.

  It uses colours to distinguish file types and metadata.
  It knows about symlinks, extended attributes, and Git.
  And it's small, fast, and just one single binary
ReleaseNotes: |-
  Bug Fixes
  - Cross-compiling by updating to libz-sys to 1.1.20
  Miscellaneous Tasks
  - Eza v0.20.8 changelogs, version bump
  Build
  - Bump palette from 0.7.5 to 0.7.6
  - Bump libc from 0.2.161 to 0.2.162
  - Bump serde from 1.0.214 to 1.0.215
ReleaseNotesUrl: https://github.com/eza-community/eza/releases/tag/v0.20.8
ManifestType: defaultLocale
ManifestVersion: 1.5.0
