# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: eza-community.eza
PackageVersion: 0.20.4
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: eza.exe
UpgradeBehavior: install
ReleaseDate: 2024-10-18
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/eza-community/eza/releases/download/v0.20.4/eza.exe_x86_64-pc-windows-gnu.zip
  InstallerSha256: 6FED1C5A2763E6A4AB03FFDB424041DFE62F96352B3B5EC3CDEF360357BDBD3C
ManifestType: installer
ManifestVersion: 1.5.0
