# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: eza-community.eza
PackageVersion: 0.20.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: eza.exe
UpgradeBehavior: install
ReleaseDate: 2024-10-31
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/eza-community/eza/releases/download/v0.20.6/eza.exe_x86_64-pc-windows-gnu.zip
  InstallerSha256: DCF52FFC3E7695F6FAB5722F131547CB33E9BA2ACF2032E2456469AA2872AE37
ManifestType: installer
ManifestVersion: 1.5.0
