# Created with WinGet Releaser v2 using Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: eza-community.eza
PackageVersion: 0.20.9
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: eza.exe
UpgradeBehavior: install
ReleaseDate: 2024-11-21
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/eza-community/eza/releases/download/v0.20.9/eza.exe_x86_64-pc-windows-gnu.zip
  InstallerSha256: B8B2A09C57E3333B272859EE0BDBFCC88344ED11F054294BC435127C23D0EEEA
ManifestType: installer
ManifestVersion: 1.5.0
